export const themes = {
  light: {
    latteBrown: {
      bg: "#FEFCF9",
      surface: "#F5EDE2",
      primary: "#C8A472",
      secondary: "#A67C52",
      accent: "#C97D72",
      text: "#3D2E20",
      "text-muted": "#9C8470",
      "text-heading": "#1A0F08",
      "text-body": "#3D2E20",
      "primary-hover": "#A67C52",
      "primary-active": "#7D5A38",
      "primary-light": "#E2C9A0",
      "primary-subtle": "#F3E4CE",
      "accent-light": "#EDCCC6",
      border: "#DDD0C0",
      "primary-content": "#1A0F08",
      "color-primary": "#C8A472",
      "color-primary-hover": "#A67C52",
      "color-primary-active": "#7D5A38",
      "color-primary-light": "#E2C9A0",
      "color-primary-subtle": "#F3E4CE",
      "color-accent": "#C97D72",
      "color-accent-light": "#EDCCC6",
      "color-background": "#FEFCF9",
      "color-surface": "#F5EDE2",
      "color-border": "#DDD0C0",
      "color-text-heading": "#1A0F08",
      "color-text-body": "#3D2E20",
      "color-text-muted": "#9C8470",
    },
    slateClean: {
      bg: "#F4F7F9",
      surface: "#FFFFFF",
      primary: "#7EC8C8",
      secondary: "#6BB6B6",
      accent: "#5B8FA8",
      text: "#4A5A6A",
      "text-muted": "#7B8A97",
      "text-heading": "#2C3E50",
      "text-body": "#4A5A6A",
      "primary-hover": "#6BB6B6",
      "primary-active": "#589FA0",
      "primary-light": "#D9F1F1",
      "primary-subtle": "#EEF9F9",
      "accent-light": "#D6E6EF",
      border: "#D6E1E8",
      "primary-content": "#2C3E50",
      "color-primary": "#7EC8C8",
      "color-primary-hover": "#6BB6B6",
      "color-primary-active": "#589FA0",
      "color-primary-light": "#D9F1F1",
      "color-primary-subtle": "#EEF9F9",
      "color-accent": "#5B8FA8",
      "color-accent-light": "#D6E6EF",
      "color-background": "#F4F7F9",
      "color-surface": "#FFFFFF",
      "color-border": "#D6E1E8",
      "color-text-heading": "#2C3E50",
      "color-text-body": "#4A5A6A",
      "color-text-muted": "#7B8A97",
    },
    lavenderMist: {
      bg: "#F8F5FC",
      surface: "#FFFFFF",
      primary: "#9B6FBF",
      secondary: "#8A5DAF",
      accent: "#2D6A4F",
      text: "#5F4C7A",
      "text-muted": "#8C7FA6",
      "text-heading": "#3F2E5C",
      "text-body": "#5F4C7A",
      "primary-hover": "#8A5DAF",
      "primary-active": "#744B96",
      "primary-light": "#E9DDF5",
      "primary-subtle": "#F5EFFB",
      "accent-light": "#D7EDE4",
      border: "#E4DBF1",
      "primary-content": "#FFFFFF",
      "color-primary": "#9B6FBF",
      "color-primary-hover": "#8A5DAF",
      "color-primary-active": "#744B96",
      "color-primary-light": "#E9DDF5",
      "color-primary-subtle": "#F5EFFB",
      "color-accent": "#2D6A4F",
      "color-accent-light": "#D7EDE4",
      "color-background": "#F8F5FC",
      "color-surface": "#FFFFFF",
      "color-border": "#E4DBF1",
      "color-text-heading": "#3F2E5C",
      "color-text-body": "#5F4C7A",
      "color-text-muted": "#8C7FA6",
    },
    warmLinen: {
      bg: "#FDF8F3",
      surface: "#FFFFFF",
      primary: "#E07B3A",
      secondary: "#CC6A2F",
      accent: "#2563A8",
      text: "#7A5132",
      "text-muted": "#A6846A",
      "text-heading": "#5A3418",
      "text-body": "#7A5132",
      "primary-hover": "#CC6A2F",
      "primary-active": "#B65A25",
      "primary-light": "#F8E1D2",
      "primary-subtle": "#FDF1EA",
      "accent-light": "#D6E3F4",
      border: "#EADFD4",
      "primary-content": "#FFFFFF",
      "color-primary": "#E07B3A",
      "color-primary-hover": "#CC6A2F",
      "color-primary-active": "#B65A25",
      "color-primary-light": "#F8E1D2",
      "color-primary-subtle": "#FDF1EA",
      "color-accent": "#2563A8",
      "color-accent-light": "#D6E3F4",
      "color-background": "#FDF8F3",
      "color-surface": "#FFFFFF",
      "color-border": "#EADFD4",
      "color-text-heading": "#5A3418",
      "color-text-body": "#7A5132",
      "color-text-muted": "#A6846A",
    },
    rosePetal: {
      bg: "#FDF2F5",
      surface: "#FFFFFF",
      primary: "#C8294A",
      secondary: "#B0213F",
      accent: "#7B5EA7",
      text: "#7A3A49",
      "text-muted": "#A87486",
      "text-heading": "#5A1E2A",
      "text-body": "#7A3A49",
      "primary-hover": "#B0213F",
      "primary-active": "#951A34",
      "primary-light": "#F6D5DD",
      "primary-subtle": "#FDECEF",
      "accent-light": "#E4DCF2",
      border: "#F0D3DA",
      "primary-content": "#FFFFFF",
      "color-primary": "#C8294A",
      "color-primary-hover": "#B0213F",
      "color-primary-active": "#951A34",
      "color-primary-light": "#F6D5DD",
      "color-primary-subtle": "#FDECEF",
      "color-accent": "#7B5EA7",
      "color-accent-light": "#E4DCF2",
      "color-background": "#FDF2F5",
      "color-surface": "#FFFFFF",
      "color-border": "#F0D3DA",
      "color-text-heading": "#5A1E2A",
      "color-text-body": "#7A3A49",
      "color-text-muted": "#A87486",
    },
    springMeadow: {
      bg: "#F3FAF5",
      surface: "#FFFFFF",
      primary: "#4CAF72",
      secondary: "#3F9B62",
      accent: "#A0632A",
      text: "#365F4A",
      "text-muted": "#6F9B86",
      "text-heading": "#1E3A2B",
      "text-body": "#365F4A",
      "primary-hover": "#3F9B62",
      "primary-active": "#347F51",
      "primary-light": "#D9F0E1",
      "primary-subtle": "#EEF8F1",
      "accent-light": "#EADBCB",
      border: "#DCEEE2",
      "primary-content": "#1E3A2B",
      "color-primary": "#4CAF72",
      "color-primary-hover": "#3F9B62",
      "color-primary-active": "#347F51",
      "color-primary-light": "#D9F0E1",
      "color-primary-subtle": "#EEF8F1",
      "color-accent": "#A0632A",
      "color-accent-light": "#EADBCB",
      "color-background": "#F3FAF5",
      "color-surface": "#FFFFFF",
      "color-border": "#DCEEE2",
      "color-text-heading": "#1E3A2B",
      "color-text-body": "#365F4A",
      "color-text-muted": "#6F9B86",
    },
    arcticBreeze: {
      bg: "#F2F8FC",
      surface: "#FFFFFF",
      primary: "#38A4D0",
      secondary: "#2F92BC",
      accent: "#B8294A",
      text: "#2E5C78",
      "text-muted": "#6F8FA3",
      "text-heading": "#123A5A",
      "text-body": "#2E5C78",
      "primary-hover": "#2F92BC",
      "primary-active": "#257BA0",
      "primary-light": "#D7EEF7",
      "primary-subtle": "#EDF7FC",
      "accent-light": "#F2D5DC",
      border: "#D6E6F0",
      "primary-content": "#123A5A",
      "color-primary": "#38A4D0",
      "color-primary-hover": "#2F92BC",
      "color-primary-active": "#257BA0",
      "color-primary-light": "#D7EEF7",
      "color-primary-subtle": "#EDF7FC",
      "color-accent": "#B8294A",
      "color-accent-light": "#F2D5DC",
      "color-background": "#F2F8FC",
      "color-surface": "#FFFFFF",
      "color-border": "#D6E6F0",
      "color-text-heading": "#123A5A",
      "color-text-body": "#2E5C78",
      "color-text-muted": "#6F8FA3",
    },
    sunsetGlow: {
      bg: "#FDF5F3",
      surface: "#FFFFFF",
      primary: "#E86A3A",
      secondary: "#D65A2B",
      accent: "#2C5FA8",
      text: "#7A3F2D",
      "text-muted": "#A87766",
      "text-heading": "#5A2618",
      "text-body": "#7A3F2D",
      "primary-hover": "#D65A2B",
      "primary-active": "#B94A21",
      "primary-light": "#FADFD3",
      "primary-subtle": "#FDF0EA",
      "accent-light": "#D6E2F4",
      border: "#F0DDD6",
      "primary-content": "#FFFFFF",
      "color-primary": "#E86A3A",
      "color-primary-hover": "#D65A2B",
      "color-primary-active": "#B94A21",
      "color-primary-light": "#FADFD3",
      "color-primary-subtle": "#FDF0EA",
      "color-accent": "#2C5FA8",
      "color-accent-light": "#D6E2F4",
      "color-background": "#FDF5F3",
      "color-surface": "#FFFFFF",
      "color-border": "#F0DDD6",
      "color-text-heading": "#5A2618",
      "color-text-body": "#7A3F2D",
      "color-text-muted": "#A87766",
    },
    goldenSand: {
      bg: "#FDFAF2",
      surface: "#FFFFFF",
      primary: "#E0A830",
      secondary: "#CC9527",
      accent: "#5B3FA8",
      text: "#7A6530",
      "text-muted": "#A8975A",
      "text-heading": "#5A4718",
      "text-body": "#7A6530",
      "primary-hover": "#CC9527",
      "primary-active": "#B07F20",
      "primary-light": "#F7E7C2",
      "primary-subtle": "#FDF6E6",
      "accent-light": "#E2DAF3",
      border: "#EFE4C9",
      "primary-content": "#5A4718",
      "color-primary": "#E0A830",
      "color-primary-hover": "#CC9527",
      "color-primary-active": "#B07F20",
      "color-primary-light": "#F7E7C2",
      "color-primary-subtle": "#FDF6E6",
      "color-accent": "#5B3FA8",
      "color-accent-light": "#E2DAF3",
      "color-background": "#FDFAF2",
      "color-surface": "#FFFFFF",
      "color-border": "#EFE4C9",
      "color-text-heading": "#5A4718",
      "color-text-body": "#7A6530",
      "color-text-muted": "#A8975A",
    },
    Sagegreen: {
      bg: "#F8F9F7",
      background: "#F8F9F7",
      surface: "#EAEDE7",
      primary: "#9CAF88",
      secondary: "#7A9167",
      accent: "#5E7350",
      text: "#3A3F37",
      "primary-hover": "#7A9167",
      "primary-active": "#5E7350",
      "primary-light": "#D9E4D3",
      "primary-subtle": "#F2F5EF",
      "primary-text": "#3D4F34",
      border: "#CDD4C7",
      "text-body": "#3A3F37",
      "text-muted": "#8C9985",
      "text-heading": "#1C2019",
    },
  },
  dark: {
    midnight: {
      bg: "#0F1226",
      surface: "#171A34",
      primary: "#6C8CFF",
      secondary: "#5A78E6",
      accent: "#E35DA1",
      text: "#B8BDE6",
      "text-muted": "#7C82B3",
      "text-heading": "#E6E9FF",
      "text-body": "#B8BDE6",
      "primary-hover": "#5A78E6",
      "primary-active": "#4862C2",
      "primary-light": "#DDE4FF",
      "primary-subtle": "#EEF1FF",
      "accent-light": "#F8D7E7",
      border: "#2A2F55",
      "primary-content": "#FFFFFF",
      "color-primary": "#6C8CFF",
      "color-primary-hover": "#5A78E6",
      "color-primary-active": "#4862C2",
      "color-primary-light": "#DDE4FF",
      "color-primary-subtle": "#EEF1FF",
      "color-accent": "#E35DA1",
      "color-accent-light": "#F8D7E7",
      "color-background": "#0F1226",
      "color-surface": "#171A34",
      "color-border": "#2A2F55",
      "color-text-heading": "#E6E9FF",
      "color-text-body": "#B8BDE6",
      "color-text-muted": "#7C82B3",
    },
    obsidian: {
      bg: "#0B0F14",
      surface: "#121821",
      primary: "#14C9B8",
      secondary: "#10B3A4",
      accent: "#F06292",
      text: "#A9C7C3",
      "text-muted": "#6E8F8A",
      "text-heading": "#E6F7F5",
      "text-body": "#A9C7C3",
      "primary-hover": "#10B3A4",
      "primary-active": "#0D9488",
      "primary-light": "#D2F5F1",
      "primary-subtle": "#E9FBF9",
      "accent-light": "#FAD4E1",
      border: "#243041",
      "primary-content": "#121821",
      "color-primary": "#14C9B8",
      "color-primary-hover": "#10B3A4",
      "color-primary-active": "#0D9488",
      "color-primary-light": "#D2F5F1",
      "color-primary-subtle": "#E9FBF9",
      "color-accent": "#F06292",
      "color-accent-light": "#FAD4E1",
      "color-background": "#0B0F14",
      "color-surface": "#121821",
      "color-border": "#243041",
      "color-text-heading": "#E6F7F5",
      "color-text-body": "#A9C7C3",
      "color-text-muted": "#6E8F8A",
    },
    slate: {
      bg: "#0F172A",
      surface: "#172033",
      primary: "#38BDF8",
      secondary: "#2DA8E0",
      accent: "#FB923C",
      text: "#B6C2D9",
      "text-muted": "#7E8BA3",
      "text-heading": "#EAF2FF",
      "text-body": "#B6C2D9",
      "primary-hover": "#2DA8E0",
      "primary-active": "#2388B8",
      "primary-light": "#D7F1FE",
      "primary-subtle": "#ECF9FF",
      "accent-light": "#FFE3CC",
      border: "#2B3A55",
      "primary-content": "#0F172A",
      "color-primary": "#38BDF8",
      "color-primary-hover": "#2DA8E0",
      "color-primary-active": "#2388B8",
      "color-primary-light": "#D7F1FE",
      "color-primary-subtle": "#ECF9FF",
      "color-accent": "#FB923C",
      "color-accent-light": "#FFE3CC",
      "color-background": "#0F172A",
      "color-surface": "#172033",
      "color-border": "#2B3A55",
      "color-text-heading": "#EAF2FF",
      "color-text-body": "#B6C2D9",
      "color-text-muted": "#7E8BA3",
    },
    carbon: {
      bg: "#111111",
      surface: "#1A1A1A",
      primary: "#A78BFA",
      secondary: "#8F74E6",
      accent: "#FB7185",
      text: "#C4C4C4",
      "text-muted": "#8A8A8A",
      "text-heading": "#F1F1F1",
      "text-body": "#C4C4C4",
      "primary-hover": "#8F74E6",
      "primary-active": "#745BC0",
      "primary-light": "#E8E1FF",
      "primary-subtle": "#F3F0FF",
      "accent-light": "#FFD6DC",
      border: "#2A2A2A",
      "primary-content": "#FFFFFF",
      "color-primary": "#A78BFA",
      "color-primary-hover": "#8F74E6",
      "color-primary-active": "#745BC0",
      "color-primary-light": "#E8E1FF",
      "color-primary-subtle": "#F3F0FF",
      "color-accent": "#FB7185",
      "color-accent-light": "#FFD6DC",
      "color-background": "#111111",
      "color-surface": "#1A1A1A",
      "color-border": "#2A2A2A",
      "color-text-heading": "#F1F1F1",
      "color-text-body": "#C4C4C4",
      "color-text-muted": "#8A8A8A",
    },
    ocean: {
      bg: "#0A192F",
      surface: "#10223F",
      primary: "#4CC9F0",
      secondary: "#38B6DB",
      accent: "#FFA62B",
      text: "#A9C3D9",
      "text-muted": "#6E8AA3",
      "text-heading": "#E6F4FF",
      "text-body": "#A9C3D9",
      "primary-hover": "#38B6DB",
      "primary-active": "#2D95B4",
      "primary-light": "#D8F4FD",
      "primary-subtle": "#ECFBFF",
      "accent-light": "#FFE6C7",
      border: "#1E3A66",
      "primary-content": "#0A192F",
      "color-primary": "#4CC9F0",
      "color-primary-hover": "#38B6DB",
      "color-primary-active": "#2D95B4",
      "color-primary-light": "#D8F4FD",
      "color-primary-subtle": "#ECFBFF",
      "color-accent": "#FFA62B",
      "color-accent-light": "#FFE6C7",
      "color-background": "#0A192F",
      "color-surface": "#10223F",
      "color-border": "#1E3A66",
      "color-text-heading": "#E6F4FF",
      "color-text-body": "#A9C3D9",
      "color-text-muted": "#6E8AA3",
    },
    charcoal: {
      bg: "#121212",
      surface: "#1C1C1C",
      primary: "#1E90FF",
      secondary: "#187FE0",
      accent: "#FF3D5A",
      text: "#C6C9D9",
      "text-muted": "#8B8FA3",
      "text-heading": "#F5F7FF",
      "text-body": "#C6C9D9",
      "primary-hover": "#187FE0",
      "primary-active": "#1366B8",
      "primary-light": "#D6E9FF",
      "primary-subtle": "#EDF5FF",
      "accent-light": "#FFD8DE",
      border: "#2F2F2F",
      "primary-content": "#FFFFFF",
      "color-primary": "#1E90FF",
      "color-primary-hover": "#187FE0",
      "color-primary-active": "#1366B8",
      "color-primary-light": "#D6E9FF",
      "color-primary-subtle": "#EDF5FF",
      "color-accent": "#FF3D5A",
      "color-accent-light": "#FFD8DE",
      "color-background": "#121212",
      "color-surface": "#1C1C1C",
      "color-border": "#2F2F2F",
      "color-text-heading": "#F5F7FF",
      "color-text-body": "#C6C9D9",
      "color-text-muted": "#8B8FA3",
    },
    graphite: {
      bg: "#151515",
      surface: "#1F1F1F",
      primary: "#9D4EDD",
      secondary: "#883CC9",
      accent: "#2EC4B6",
      text: "#C9C4D9",
      "text-muted": "#918AA3",
      "text-heading": "#F3F0FF",
      "text-body": "#C9C4D9",
      "primary-hover": "#883CC9",
      "primary-active": "#6E30A4",
      "primary-light": "#EAD9FB",
      "primary-subtle": "#F5EDFF",
      "accent-light": "#D6F3F0",
      border: "#313131",
      "primary-content": "#FFFFFF",
      "color-primary": "#9D4EDD",
      "color-primary-hover": "#883CC9",
      "color-primary-active": "#6E30A4",
      "color-primary-light": "#EAD9FB",
      "color-primary-subtle": "#F5EDFF",
      "color-accent": "#2EC4B6",
      "color-accent-light": "#D6F3F0",
      "color-background": "#151515",
      "color-surface": "#1F1F1F",
      "color-border": "#313131",
      "color-text-heading": "#F3F0FF",
      "color-text-body": "#C9C4D9",
      "color-text-muted": "#918AA3",
    },
    void: {
      bg: "#0A0A0A",
      surface: "#141414",
      primary: "#60A5FA",
      secondary: "#4C90E6",
      accent: "#FB8C00",
      text: "#B8C2D9",
      "text-muted": "#7F889F",
      "text-heading": "#EAF2FF",
      "text-body": "#B8C2D9",
      "primary-hover": "#4C90E6",
      "primary-active": "#3C73BB",
      "primary-light": "#DCEBFF",
      "primary-subtle": "#EEF4FF",
      "accent-light": "#FFE2C2",
      border: "#262626",
      "primary-content": "#0A0A0A",
      "color-primary": "#60A5FA",
      "color-primary-hover": "#4C90E6",
      "color-primary-active": "#3C73BB",
      "color-primary-light": "#DCEBFF",
      "color-primary-subtle": "#EEF4FF",
      "color-accent": "#FB8C00",
      "color-accent-light": "#FFE2C2",
      "color-background": "#0A0A0A",
      "color-surface": "#141414",
      "color-border": "#262626",
      "color-text-heading": "#EAF2FF",
      "color-text-body": "#B8C2D9",
      "color-text-muted": "#7F889F",
    },
    twilight: {
      bg: "#141225",
      surface: "#1D1A33",
      primary: "#8B7CF6",
      secondary: "#7768DE",
      accent: "#F4A261",
      text: "#C5C1E0",
      "text-muted": "#8F8BA8",
      "text-heading": "#EEEAFE",
      "text-body": "#C5C1E0",
      "primary-hover": "#7768DE",
      "primary-active": "#6054B8",
      "primary-light": "#E4E0FF",
      "primary-subtle": "#F2F0FF",
      "accent-light": "#FFE4CC",
      border: "#302C4D",
      "primary-content": "#FFFFFF",
      "color-primary": "#8B7CF6",
      "color-primary-hover": "#7768DE",
      "color-primary-active": "#6054B8",
      "color-primary-light": "#E4E0FF",
      "color-primary-subtle": "#F2F0FF",
      "color-accent": "#F4A261",
      "color-accent-light": "#FFE4CC",
      "color-background": "#141225",
      "color-surface": "#1D1A33",
      "color-border": "#302C4D",
      "color-text-heading": "#EEEAFE",
      "color-text-body": "#C5C1E0",
      "color-text-muted": "#8F8BA8",
    },
    onyx: {
      bg: "#0D0D0D",
      surface: "#161616",
      primary: "#00E5A8",
      secondary: "#00CC95",
      accent: "#FF006E",
      text: "#B6E6DA",
      "text-muted": "#7AAFA3",
      "text-heading": "#EFFFFA",
      "text-body": "#B6E6DA",
      "primary-hover": "#00CC95",
      "primary-active": "#00A878",
      "primary-light": "#CCF8EA",
      "primary-subtle": "#E6FFF7",
      "accent-light": "#FFD6E7",
      border: "#292929",
      "primary-content": "#161616",
      "color-primary": "#00E5A8",
      "color-primary-hover": "#00CC95",
      "color-primary-active": "#00A878",
      "color-primary-light": "#CCF8EA",
      "color-primary-subtle": "#E6FFF7",
      "color-accent": "#FF006E",
      "color-accent-light": "#FFD6E7",
      "color-background": "#0D0D0D",
      "color-surface": "#161616",
      "color-border": "#292929",
      "color-text-heading": "#EFFFFA",
      "color-text-body": "#B6E6DA",
      "color-text-muted": "#7AAFA3",
    },
  },
};

export function applyTheme(darkMode: boolean, themeName?: string) {
  const root = document.documentElement;
  let theme;

  // Validate themeName exists in the current mode
  const modeThemes = darkMode ? themes.dark : themes.light;
  if (themeName && themeName in modeThemes) {
    theme = modeThemes[themeName as keyof typeof modeThemes];
  } else {
    // Fallback to default themes if name is invalid or not provided
    theme = darkMode ? themes.dark.twilight : themes.light.warmLinen;
  }

  if (theme) {
    const hasThemeVar = (key: string) =>
      Object.prototype.hasOwnProperty.call(theme, key);

    // Set core CSS variables used by index.css and components
    for (const [key, value] of Object.entries(theme)) {
      root.style.setProperty(`--${key}`, value);
    }

    // Generate derived colors for consistency
    // We can use the primary color with different opacities for muted/hover states if not provided
    if (!hasThemeVar("primary-hover")) {
      root.style.setProperty("--primary-hover", `${theme.primary}dd`);
    }
    if (!hasThemeVar("text-muted")) {
      root.style.setProperty("--text-muted", darkMode ? "#9d97b0" : "#a8a29e");
    }
    if (!hasThemeVar("border")) {
      root.style.setProperty(
        "--border",
        darkMode ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.1)",
      );
    }
    if (!hasThemeVar("primary-content")) {
      root.style.setProperty("--primary-content", "#ffffff");
    }
    root.style.setProperty(
      "--border-strong",
      darkMode ? "rgba(255,255,255,0.2)" : "rgba(0,0,0,0.2)",
    );
  }

  // Add/remove dark class for Tailwind and global styles
  if (darkMode) {
    root.classList.add("dark");
  } else {
    root.classList.remove("dark");
  }
}
