const { fontFamily } = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var", "Inter", ...fontFamily.sans],
      },
      borderRadius: {
        DEFAULT: "8px",
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "18px",
        "2xl": "22px",
        "3xl": "28px",
        full: "9999px",
      },
      colors: {
        // Existing Themes
        linen: {
          bg: "#fef7f0",
          surface: "#fffbf5",
          primary: "#d97706",
          "primary-hover": "#b45309",
          secondary: "#ea580c",
          accent: "#0284c7",
          text: "#292524",
          muted: "#a8a29e",
          border: "#e7ddd2",
          "border-strong": "#d6cec1",
        },
        twilight: {
          bg: "#141225",
          surface: "#1D1A33",
          "surface-2": "#F2F0FF",
          primary: "#8B7CF6",
          "primary-hover": "#7768DE",
          secondary: "#7768DE",
          accent: "#F4A261",
          text: "#C5C1E0",
          muted: "#8F8BA8",
          border: "#302C4D",
          "border-strong": "#8B7CF6",
        },

        // New Dark Themes
        midnight: {
          bg: "#0F1226",
          surface: "#171A34",
          "surface-2": "#EEF1FF",
          primary: "#6C8CFF",
          "primary-hover": "#5A78E6",
          secondary: "#5A78E6",
          accent: "#E35DA1",
          text: "#B8BDE6",
          muted: "#7C82B3",
          border: "#2A2F55",
          "border-strong": "#6C8CFF",
        },
        obsidian: {
          bg: "#0B0F14",
          surface: "#121821",
          "surface-2": "#E9FBF9",
          primary: "#14C9B8",
          "primary-hover": "#10B3A4",
          secondary: "#10B3A4",
          accent: "#F06292",
          text: "#A9C7C3",
          muted: "#6E8F8A",
          border: "#243041",
          "border-strong": "#14C9B8",
        },
        slate: {
          bg: "#0F172A",
          surface: "#172033",
          "surface-2": "#ECF9FF",
          primary: "#38BDF8",
          "primary-hover": "#2DA8E0",
          secondary: "#2DA8E0",
          accent: "#FB923C",
          text: "#B6C2D9",
          muted: "#7E8BA3",
          border: "#2B3A55",
          "border-strong": "#38BDF8",
        },
        carbon: {
          bg: "#111111",
          surface: "#1A1A1A",
          "surface-2": "#F3F0FF",
          primary: "#A78BFA",
          "primary-hover": "#8F74E6",
          secondary: "#8F74E6",
          accent: "#FB7185",
          text: "#C4C4C4",
          muted: "#8A8A8A",
          border: "#2A2A2A",
          "border-strong": "#A78BFA",
        },
        ocean: {
          bg: "#0A192F",
          surface: "#10223F",
          "surface-2": "#ECFBFF",
          primary: "#4CC9F0",
          "primary-hover": "#38B6DB",
          secondary: "#38B6DB",
          accent: "#FFA62B",
          text: "#A9C3D9",
          muted: "#6E8AA3",
          border: "#1E3A66",
          "border-strong": "#4CC9F0",
        },
        charcoal: {
          bg: "#121212",
          surface: "#1C1C1C",
          "surface-2": "#EDF5FF",
          primary: "#1E90FF",
          "primary-hover": "#187FE0",
          secondary: "#187FE0",
          accent: "#FF3D5A",
          text: "#C6C9D9",
          muted: "#8B8FA3",
          border: "#2F2F2F",
          "border-strong": "#1E90FF",
        },
        graphite: {
          bg: "#151515",
          surface: "#1F1F1F",
          "surface-2": "#F5EDFF",
          primary: "#9D4EDD",
          "primary-hover": "#883CC9",
          secondary: "#883CC9",
          accent: "#2EC4B6",
          text: "#C9C4D9",
          muted: "#918AA3",
          border: "#313131",
          "border-strong": "#9D4EDD",
        },
        void: {
          bg: "#0A0A0A",
          surface: "#141414",
          "surface-2": "#EEF4FF",
          primary: "#60A5FA",
          "primary-hover": "#4C90E6",
          secondary: "#4C90E6",
          accent: "#FB8C00",
          text: "#B8C2D9",
          muted: "#7F889F",
          border: "#262626",
          "border-strong": "#60A5FA",
        },
        onyx: {
          bg: "#0D0D0D",
          surface: "#161616",
          "surface-2": "#E6FFF7",
          primary: "#00E5A8",
          "primary-hover": "#00CC95",
          secondary: "#00CC95",
          accent: "#FF006E",
          text: "#B6E6DA",
          muted: "#7AAFA3",
          border: "#292929",
          "border-strong": "#00E5A8",
        },

        // New Light Themes
        cloudMinimal: {
          bg: "#FEFCF9",
          surface: "#F5EDE2",
          "surface-2": "#DDD0C0",
          primary: "#C8A472",
          "primary-hover": "#A67C52",
          secondary: "#A67C52",
          accent: "#C97D72",
          text: "#3D2E20",
          muted: "#9C8470",
          border: "#DDD0C0",
          "border-strong": "#C8A472",
        },
        slateClean: {
          bg: "#F4F7F9",
          surface: "#FFFFFF",
          "surface-2": "#EEF9F9",
          primary: "#7EC8C8",
          "primary-hover": "#6BB6B6",
          secondary: "#6BB6B6",
          accent: "#5B8FA8",
          text: "#4A5A6A",
          muted: "#7B8A97",
          border: "#D6E1E8",
          "border-strong": "#7EC8C8",
        },
        lavenderMist: {
          bg: "#F8F5FC",
          surface: "#FFFFFF",
          "surface-2": "#F5EFFB",
          primary: "#9B6FBF",
          "primary-hover": "#8A5DAF",
          secondary: "#8A5DAF",
          accent: "#2D6A4F",
          text: "#5F4C7A",
          muted: "#8C7FA6",
          border: "#E4DBF1",
          "border-strong": "#9B6FBF",
        },
        warmLinen: {
          bg: "#FDF8F3",
          surface: "#FFFFFF",
          "surface-2": "#FDF1EA",
          primary: "#E07B3A",
          "primary-hover": "#CC6A2F",
          secondary: "#CC6A2F",
          accent: "#2563A8",
          text: "#7A5132",
          muted: "#A6846A",
          border: "#EADFD4",
          "border-strong": "#E07B3A",
        },
        rosePetal: {
          bg: "#FDF2F5",
          surface: "#FFFFFF",
          "surface-2": "#FDECEF",
          primary: "#C8294A",
          "primary-hover": "#B0213F",
          secondary: "#B0213F",
          accent: "#7B5EA7",
          text: "#7A3A49",
          muted: "#A87486",
          border: "#F0D3DA",
          "border-strong": "#C8294A",
        },
        springMeadow: {
          bg: "#F3FAF5",
          surface: "#FFFFFF",
          "surface-2": "#EEF8F1",
          primary: "#4CAF72",
          "primary-hover": "#3F9B62",
          secondary: "#3F9B62",
          accent: "#A0632A",
          text: "#365F4A",
          muted: "#6F9B86",
          border: "#DCEEE2",
          "border-strong": "#4CAF72",
        },
        arcticBreeze: {
          bg: "#F2F8FC",
          surface: "#FFFFFF",
          "surface-2": "#EDF7FC",
          primary: "#38A4D0",
          "primary-hover": "#2F92BC",
          secondary: "#2F92BC",
          accent: "#B8294A",
          text: "#2E5C78",
          muted: "#6F8FA3",
          border: "#D6E6F0",
          "border-strong": "#38A4D0",
        },
        sunsetGlow: {
          bg: "#FDF5F3",
          surface: "#FFFFFF",
          "surface-2": "#FDF0EA",
          primary: "#E86A3A",
          "primary-hover": "#D65A2B",
          secondary: "#D65A2B",
          accent: "#2C5FA8",
          text: "#7A3F2D",
          muted: "#A87766",
          border: "#F0DDD6",
          "border-strong": "#E86A3A",
        },
        goldenSand: {
          bg: "#FDFAF2",
          surface: "#FFFFFF",
          "surface-2": "#FDF6E6",
          primary: "#E0A830",
          "primary-hover": "#CC9527",
          secondary: "#CC9527",
          accent: "#5B3FA8",
          text: "#7A6530",
          muted: "#A8975A",
          border: "#EFE4C9",
          "border-strong": "#E0A830",
        },
        mintFresh: {
          bg: "#f0fdfa",
          surface: "#ccfbf1",
          "surface-2": "#99f6e4",
          primary: "#0f766e",
          "primary-hover": "#115e59",
          secondary: "#0d9488",
          accent: "#b91c1c",
          text: "#042f2e",
          muted: "#14b8a6",
          border: "#99f6e4",
          "border-strong": "#5eead4",
        },
      },
      boxShadow: {
        sm: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        DEFAULT: "0 2px 8px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.05)",
        md: "0 4px 16px rgba(0,0,0,0.10), 0 2px 6px rgba(0,0,0,0.06)",
        lg: "0 8px 32px rgba(0,0,0,0.12), 0 4px 12px rgba(0,0,0,0.08)",
        "dark-sm": "0 1px 3px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.2)",
        "dark-md": "0 4px 16px rgba(0,0,0,0.4), 0 2px 6px rgba(0,0,0,0.3)",
        "dark-lg": "0 8px 32px rgba(0,0,0,0.5), 0 4px 12px rgba(0,0,0,0.35)",
      },
      transitionTimingFunction: {
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        bounce: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        fall: {
          "0%": { transform: "translateY(-60px) rotate(0deg)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "0.8" },
          "100%": {
            transform: "translateY(110vh) rotate(360deg)",
            opacity: "0",
          },
        },
        breathe: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(251, 191, 36, 0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(251, 191, 36, 0)" },
        },
        softScale: {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.05)" },
        },
        ringPulse: {
          "0%": { boxShadow: "0 0 0 0 rgba(16, 185, 129, 0.4)" },
          "100%": { boxShadow: "0 0 0 6px rgba(16, 185, 129, 0)" },
        },
      },
      animation: {
        "fade-in": "fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "slide-up": "slideUp 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "slide-down": "slideDown 0.3s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        "scale-in": "scaleIn 0.25s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        shimmer: "shimmer 1.8s infinite",
        fall: "fall 4s linear forwards",
        breathe: "breathe 2.5s ease-in-out infinite",
        "soft-scale": "softScale 2s ease-in-out infinite",
        "ring-pulse": "ringPulse 1.5s ease-out infinite",
      },
    },
  },
  plugins: [],
};
